# Links to be made for tools and scripts
links:
  tracking_tools: auto
  modules: tracking_tools/lhcmask
  tools: tracking_tools/lhctoolkit
  #beambeam_macros: tracking_tools/beambeam_macros
  errors: tracking_tools/lhcerrors
  optics_repository: /afs/cern.ch/eng/lhc/optics

# Mode - choose between:

#    Main modes:
#    'b1_without_bb'
#    'b1_with_bb'
#    'b4_from_b2_without_bb'
#    'b4_from_b2_with_bb'

#    Legacy modes
#     'b1_with_bb_legacy_macros
#     'b4_without_bb'

mode: b1_with_bb

# For test against madx mask for modes
# 'b4_from_b2_without_bb' and 'b4_without_bb':
# force_leveling:
#       on_sep8: -0.03425547139366354
#       on_sep2: 0.14471680504084292

# Optics file
optics_file: optics_repository/HLLHCV1.5/flatcc/opt_flathv_75_180_1500_thin.madx
# Optics version
optics_version: '1.5'

# Enable checks
check_betas_at_ips: false
check_separations_at_ips: false
save_intermediate_twiss: false

# Tolerances for checks [ip1, ip2, ip5, ip8]
tol_beta:
- 0.003
- 0.2
- 0.003
- 0.02
tol_sep:
- 1.0e-06
- 1.0e-06
- 1.0e-06
- 1.0e-06

# Tolerance for check on flat machine
tol_co_flatness: 1.0e-06

# Beam parameters
beam_norm_emit_x: 2.5 # [um]
beam_norm_emit_y: 2.5 # [um]
beam_sigt: 0.0761 # [m]
beam_sige: 0.00011
beam_npart: 140000000000.0
beam_energy_tot: 7000 # [GeV]

# Tunes and chromaticities
qx0: 62.316
qy0: 60.321
chromaticity_x: 15
chromaticity_y: 15

# RF voltage
vrf_total: 16.0 # [MV]

# Octupole current
oct_current: 60.0 # [A]

# Luminosity parameters
enable_lumi_control: true
sep_plane_ip2: x # used by python tools - NOT by legacy macros
sep_plane_ip8: y # used by python tools - NOT by legacy macros,
lumi_ip8: 2.0e+33 # [Hz/cm2] leveled luminosity in IP8
fullsep_in_sigmas_ip2: 5
nco_IP1: 1960 # number of Head-On collisions in IP1
nco_IP2: 1178 # number of Head-On collisions in IP2
nco_IP5: 1960 # number of Head-On collisions in IP5
nco_IP8: 1886 # number of Head-On collisions in IP8

# Beam-beam parameters (used by python tools - NOT by legacy macros)
beambeam_config:
  numberOfLRPerIRSide:
  - 25
  - 20
  - 25
  - 20
  bunch_spacing_buckets: 10
  numberOfHOSlices: 11
  bunch_num_particles:
  bunch_particle_charge:
  sigmaz_m:
  z_crab_twiss: 0.075
  filling_scheme_json: /afs/cern.ch/work/c/cdroin/private/DA_study/master_study/master_jobs/filling_scheme/8b4e_1972b_1960_1178_1886_224bpi_12inj_800ns_bs200ns.json
  bunch_to_track: 13
match_q_dq_with_bb: false # should be off at collision

# Enable crab cavities
enable_crabs: true

# N. iterations for coupling correction
N_iter_coupling: 2

# Value to be added to linear coupling knobs (on sequence_to_track)
delta_cmr: 0.001
delta_cmi: 0.0

# Verbose flag for MAD-X parts
verbose_mad_parts: true

# Optics-specific knob namings
knob_names:
  # Common knobs
  sepknob_ip2_mm: on_sep2
  sepknob_ip8_mm: on_sep8

  # Knobs associated to sequences
  qknob_1:
    lhcb1: kqtf.b1
    lhcb2: kqtf.b2
  qknob_2:
    lhcb1: kqtd.b1
    lhcb2: kqtd.b2
  chromknob_1:
    lhcb1: ksf.b1
    lhcb2: ksf.b2
  chromknob_2:
    lhcb1: ksd.b1
    lhcb2: ksd.b2
  cmrknob:
    lhcb1: cmrskew
    lhcb2: cmrskew
  cmiknob:
    lhcb1: cmiskew
    lhcb2: cmiskew

# Optics specific knob values
# (only on_disp, on_crab1 and on_crab5 are used directly by the mask,
# the other values are used only throught the optics_specific_tools file)
knob_settings:
  # IP specific orbit settings
  on_x1: 250.0
  on_sep1: 0
  on_x2: -170
  on_sep2: 0.138
  on_x5: 250.0
  on_sep5: 0
  on_x8h: 0.0
  on_x8v: 170
  on_sep8h: 0
  on_sep8v: 0
  on_a1: 0
  on_o1: 0
  on_a2: 0
  on_o2: 0
  on_a5: 0
  on_o5: 0
  on_a8: 0
  on_o8: 0
  on_crab1: -190
  on_crab5: -190
  on_disp: 1
  on_alice_normalized: 1
  on_lhcb_normalized: 1
  on_sol_atlas: 0
  on_sol_cms: 0
  on_sol_alice: 0
enable_imperfections: false

# Enable knob synthesis (for coupling correction, if no imperfections)
enable_knob_synthesis: true

# Parameters for machine imperfections
pars_for_imperfections:
  par_myseed: 1
  par_correct_for_D2: 0
  par_correct_for_MCBX: 0
  par_on_errors_LHC: 1
  par_off_errors_Q4_inIP15: 0
  par_off_errors_Q5_inIP15: 0
  par_on_errors_MBH: 1
  par_on_errors_Q4: 1
  par_on_errors_D2: 1
  par_on_errors_D1: 1
  par_on_errors_IT: 1
  par_on_errors_MCBRD: 0
  par_on_errors_MCBXF: 0
  par_on_errors_NLC: 0
  par_write_errortable: 1

# Parameters for legacy beam-beam macros (not used in default modes)
pars_for_legacy_bb_macros:
  par_b_t_dist: 25.0 # bunch spacing [ns]
  par_n_inside_D1: 5 # n. parasitic encounters inside D1
log_file: /afs/cern.ch/work/c/cdroin/private/DA_study/master_study/opt_flathv_75_1500_withBB_chroma15_1p4_all_bunches/madx_001/tree_maker.log
